//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MerchantApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ware
    {
        public int Id { get; set; }
        public int Price { get; set; }
        public string Item_Name { get; set; }
        public string Item_Origin { get; set; }
    }
}
